version: '3.3'

services:
  proxy:
    build:
      context: ./docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
